[package]
name = "opendata-download-radar"
version = "0.1.0"
authors = ["Niclas Kron <niclas.kroon@protonmail.ch>"]
edition = "2018"

[[bin]]
name = "opendata-download-radar"
path = "src/main.rs"

[dependencies]
image = "0.21.0"
rocket = "0.4.0"
reqwest = "0.9.6"
rand = "0.6.5"